// Generated by the lithium symbol generator.
#include <lithium_symbol.hh>
#ifndef LI_SYMBOL_hostname
#define LI_SYMBOL_hostname
    LI_SYMBOL(hostname)
#endif

#ifndef LI_SYMBOL_id
#define LI_SYMBOL_id
    LI_SYMBOL(id)
#endif

#ifndef LI_SYMBOL_name
#define LI_SYMBOL_name
    LI_SYMBOL(name)
#endif

#ifndef LI_SYMBOL_password
#define LI_SYMBOL_password
    LI_SYMBOL(password)
#endif

#ifndef LI_SYMBOL_timeout
#define LI_SYMBOL_timeout
    LI_SYMBOL(timeout)
#endif

#ifndef LI_SYMBOL_up
#define LI_SYMBOL_up
    LI_SYMBOL(up)
#endif

#ifndef LI_SYMBOL_username
#define LI_SYMBOL_username
    LI_SYMBOL(username)
#endif

